---
- name: Reload systemd for 3proxy
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart 3proxy
  ansible.builtin.service:
    name: "{{ proxy3_service_name }}"
    state: restarted

- name: Persist iptables rules
  ansible.builtin.command: netfilter-persistent save
  changed_when: true
